### ISSUE TITLE
Checking existing event before create new one

### ISSUE THREAD

**Issue by OskarLebuda** [stepek/kodilla-calendar-sync-ext#1]
Przed stworzeniem nowego wydarzenia powinieneś sprawdzać czy takie wydarzenie czy taki kursant nie ma wydarzenia już. Już mówię dlaczego.

Zdarza się, że kursanci przekładają spotkanie. Np dziś mamy poniedziałek, rozmowę mamy we wtorek, a kursant pisze w poniedziałek i mówi, że chce pogadać w piątek zamiast wtorek.

Rozwiązanie jest tylko jedno. Przed dodaniem nowego eventu trzeba sprawdzić czy taki już przypadkiem nie istnieje. Jeśli istnieje JAKIEKOLWIEK event, który zawiera string
```
Rozmowa - ${request.source.name}
```
 powinien zbierać jego `id` i wywalać. Te wszystkie operacje można załatwić eventami google calendar: `list`, `delete`

**Comment by stepek** [comment]
Dzięki za issue nasi najlepsi ludzie tym się zajmują :)
Faktycznie sprawia to troche problemów i warto to dodać 👍
